### ISSUE TITLE
Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch (code: 123)

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/developer#103]
**Description / Beschreibung**
Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch (code: 123)

Modulname:
`translate:bs5_module_staff`

Übersetzung
`bs5_module_staff = Mitarbeiter∗innen`

**Affected versions / Verwendete Versionen**

REDAXO: 5.14.1
PHP: 8.1.6
Database: MySQL/MariaDB
Browser: *
AddOns: developer

**Did it whoops? / Whoops erhalten?**
**ErrorException:** rename(C:\xampp816\htdocs\xxx.com\src\/modules/(translatebs5_module_staff_list) [29],C:\xampp816\htdocs\xxx.com\src\/modules/Mitarbeiter*innen [29]): Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch (code: 123)
**File:** src\addons\developer\lib\synchronizer.php
**Line:** 167

<details>
<summary>Stacktrace</summary>

| Function                                             | File                                                | Line     |
| ---------------------------------------------------- | --------------------------------------------------- | -------- |
| rex_error_handler::handleError                       |                                                     |          |
| rename                                               | src\addons\developer\lib\synchronizer.php           | 167      |
| rex_developer_synchronizer->synchronizeReceivedItems | src\addons\developer\lib\synchronizer.php           | 91       |
| rex_developer_synchronizer->run                      | src\addons\developer\lib\manager.php                | 185      |
| rex_developer_manager::{closure}                     |                                                     |          |
| array_walk                                           | src\addons\developer\lib\manager.php                | 192      |
| rex_developer_manager::synchronize                   | src\addons\developer\lib\manager.php                | 168      |
| rex_developer_manager::start                         | src\addons\developer\boot.php                       | 25       |
| rex_package->{closure}                               | src\core\lib\extension.php                          | 52       |
| rex_extension::{closure}                             | src\core\lib\util\timer.php                         | 63       |
| rex_timer::measure                                   | src\core\lib\extension.php                          | 63       |
| rex_extension::registerPoint                         | src\addons\debug\lib\extensions\extension_debug.php | 24       |
| rex_extension_debug::registerPoint                   | src\core\lib\extension.php                          | 37       |
| rex_extension::registerPoint                         | src\core\packages.php                               | 33       |
| include_once                                         | src\core\backend.php                                | 201      |
| require                                              | src\core\boot.php                                   | 143      |
| require                                              | public\redaxo\index.php                             | 12       |

</details>
<details>
<summary>System report (REDAXO 5.14.1, PHP 8.1.6, MariaDB 10.4.24)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.14.1     |

| PHP           |                                |
| ------------: | :----------------------------- |
|       Version | 8.1.6                          |
|       OPcache | no                             |
|        Xdebug | no                             |
|       Warning | The setup will continue without SSL encryption. It is recommended to use SSL encryption for each call to the front- and backend in order to ensure privacy and data protection. |

| Database      |                 |
| ------------: | :-------------- |
|       Version | MariaDB 10.4.24 |
| Character set | utf8mb4         |

| Server        |                |
| ------------: | :------------- |
|            OS | WINNT          |
|          SAPI | apache2handler |
|     Webserver | Apache/2.4.53  |

| Request       |                  |
| ------------: | :--------------- |
|       Browser | Chrome/107.0.0.0 |
|      Protocol | HTTP/1.1         |
|         HTTPS | no               |

| Packages                 |             |
| -----------------------: | :---------- |
|             accessdenied | 2.0.2       |
|                  adminer | 1.9.2       |
|              auto_delete | 1.0-dev     |
|                   backup | 2.8.2       |
|              be_password | 2.0.1       |
|                 be_style | 3.1.0       |
|          be_style/redaxo | 3.1.0       |
|          be_style_fluent | 4.0.0       |
|                  bloecks | 3.1.1       |
|         bloecks/cutncopy | 3.1.1       |
|             cache_warmup | 4.0.0       |
|          consent_manager | 4.0.0beta3  |
|                  cronjob | 2.9.0       |
|                    debug | 1.2.2       |
|                developer | 3.9.1       |
|               focuspoint | 4.0.2       |
|          global_settings | 2.8.2       |
|                  install | 2.10.0      |
|           mailer_profile | 1.0.1       |
|              maintenance | 2.8.5       |
|            media_manager | 2.13.0      |
| media_manager_responsive | 1.1.0-dev   |
|                mediapool | 2.12.0      |
|                 metainfo | 2.9.0       |
|                    mform | 7.2.4       |
|                    neues | 2.0.0-beta3 |
|                phpmailer | 2.11.2      |
|                 plus_bs5 | 0.0.5       |
|                  project | dev         |
|          project_manager | 1.4.0       |
|   project_manager/client | 1.1.0       |
|                    qanda | 2.0.11      |
|         quick_navigation | 6.0.1       |
|                 redactor | 2.3.0       |
|                 speed_up | 1.3.1       |
|                    sprog | 1.4.0       |
|                    staff | 1.2.1       |
|                structure | 2.14.1      |
|        structure/content | 2.14.1      |
|                 techwire | dev         |
|                      url | 2.0.2       |
|                    users | 2.9.0       |
|                   watson | 2.3.0       |
|                  ydeploy | 1.1.1       |
|                    yform | 4.0.4       |
|              yform/email | 4.0.4       |
|            yform/manager | 4.0.4       |
|              yform_field | 2.1.2       |
|    yform_spam_protection | 2.0.0-beta  |
|          yform_usability | 2.0.5       |
|                 yrewrite | 2.9.1       |
|        yrewrite_metainfo | 1.0.5       |
|              zip_install | 1.2         |

</details>

**Comment by gharlan** [comment]
Das kapiere ich nicht. Bei mir wird das Sternchen entfernt, und so [steht es auch im Code](https://github.com/FriendsOfREDAXO/developer/blob/abd8f0b7c1e9cf6672938d190e3a067f3df4cc30/lib/synchronizer.php#L293).

Kannst du eventuell bei dir weiter analysieren, ob "Mitarbeiter*innen" bei dir durch die Zeile geht, und ob bei dir dann dort das Sternchen erhalten bleibt?

**Comment by alxndr-w** [comment]
Achtung, es ist das mathematische Stern-Zeichen, also ein Sonderzeichen aus dem UTF8-Bereich: `∗` nicht `*`

Mir geht's da allerdings nicht ums Sternchen, sondern generell, dass eine Übersetzung mit solchen Sonderzeichen nicht zu diesem Fehler führen darf.

**Comment by alxndr-w** [comment]
Imho dürfte gar nicht die von der Admin-Benutzersprache gewählte Übersetzung im Dateinamen landen, sondern der Key ohne `translate:` vorne dran.

Das Modul wurde über das REDAXO -Backend erstellt, falls relevant.

**Comment by gharlan** [comment]
Mir war zwar aufgefallen, dass das Sternchen tief sitzt hier auf Github, beim Kopieren wurde es bei mir aber anscheinend doch in das normale Sternchen gewandelt.
Nun noch mal getestet mit dem gleichen Sternchen wie bei dir. Da wird es in der Tat nicht entfernt, sondern in das normale Sternchen umgewandelt. Führt auf dem Mac nicht zu Problemen, aber auf Windows ist es ein nicht erlaubtes Zeichen in Dateinamen. Das muss ich fixen.

> mho dürfte gar nicht die von der Admin-Benutzersprache gewählte Übersetzung im Dateinamen landen, sondern der Key ohne `translate:` vorne dran.

Das hatte sich Thomas hier gewünscht: https://github.com/FriendsOfREDAXO/developer/issues/42
Ich habe da aktuell keine klare Meinung zu, werde es daher erstmal beim Status Quo lassen. 
Aber das eigentliche Problem mit dem Sternchen (was auch ohne Übersetzung passieren würde, wenn das Sternchen direkt im Name drin wäre) werde ich fixen.

**Comment by alxndr-w** [comment]
Thx
