### ISSUE TITLE
PHP 8: `str_replace()`: Passing null … is deprecated, wenn data-Ordner nicht existiert

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/developer#104]
Das Problem tritt auf, wenn der Data-Ordner nicht existiert. Dann ist `$filename1` innerhalb von `equalFilenames()` gleich `null`.

Innerhalb der beiden Demos, die den Developer benutzen, nämlich Onepage und Community, wird nach Installation der benötigten AddOns der data-Ordner des Developers gelöscht, um zu verhindern, dass dieser bei der Initialisierung alte Inhalte aggregiert:
https://github.com/FriendsOfREDAXO/demo_onepage/blob/5f70ce1bb40e889ab6f0bb3354a4214b84f3fe71/lib/demo_onepage.php#L140-L143

---

**ErrorException:** str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated
**File:** redaxo/src/addons/developer/lib/synchronizer.php
**Line:** 317

<details>
<summary>Stacktrace</summary>

| Function                                             | File                                             | Line     |
| ---------------------------------------------------- | ------------------------------------------------ | -------- |
| rex_error_handler::handleError                       |                                                  |          |
| str_replace                                          | redaxo/src/addons/developer/lib/synchronizer.php | 317      |
| rex_developer_synchronizer::equalFilenames           | redaxo/src/addons/developer/lib/synchronizer.php | 159      |
| rex_developer_synchronizer->synchronizeReceivedItems | redaxo/src/addons/developer/lib/synchronizer.php | 91       |
| rex_developer_synchronizer->run                      | redaxo/src/addons/developer/lib/manager.php      | 184      |
| rex_developer_manager::{closure}                     |                                                  |          |
| array_walk                                           | redaxo/src/addons/developer/lib/manager.php      | 191      |
| rex_developer_manager::synchronize                   | redaxo/src/addons/developer/lib/manager.php      | 167      |
| rex_developer_manager::start                         | redaxo/src/addons/developer/boot.php             | 21       |
| rex_package->{closure}                               | redaxo/src/core/lib/extension.php                | 52       |
| rex_extension::{closure}                             | redaxo/src/core/lib/util/timer.php               | 63       |
| rex_timer::measure                                   | redaxo/src/core/lib/extension.php                | 42       |
| rex_extension::registerPoint                         | redaxo/src/core/packages.php                     | 33       |
| include_once                                         | redaxo/src/core/backend.php                      | 201      |
| require                                              | redaxo/src/core/boot.php                         | 143      |
| require                                              | redaxo/index.php                                 | 9        |

</details>

**Comment by olien** [comment]
DAs gleiche Problem habe ich gerade auch.
