### ISSUE TITLE
YDeploy + developer - bei Whoops o.ä. wird in `/src/*` + und `/data/addons/developer/*` synchronisiert

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/developer#108]
**Description / Beschreibung**
Ich kann nur ganz grob beschreiben, dass developer gelegentlich in einem YDeploy-Projekt in einen vollkommen verkehrten Pfad, nämlich `/src/` die Module und Templates schreibt, obwohl der Pfad eigentlich überschrieben werden sollte.

**Comment by tbaddade** [comment]
Du meinst, dass nach einem Deploy die Daten in `/src/` liegen und nicht wie du es konfiguriert hast?

Kannst du noch weitere Infos liefern? 
- Genauer Unterschied Lokal … Server
- Nutzt du einen eigenen Path Provider? Wie sieht dieser aus? 
- Core/AddOns aktuell?
- Wie kann man es nachstellen? Wir hatten das noch nie, aber bei uns liegen auch die Daten tatsächlich in `/src/`, sodass wir es bisher gar nicht mitbekommen hätten.

Wäre das nicht eher ein Issue für YDeploy?

**Comment by alxndr-w** [comment]
Das ist möglich, dass das so gedacht ist - dann wäre das Problem eher umgekehrt, dass eben nicht immer `/src/` verwendet würde, sondern auch module / templates wieder in den data-Ordner synchronisiert werden, wo sie dann nicht sein sollten.

Momentan habe ich im src-Ordner und im-Data-Ordner Kopien meiner Module und Templates.

**Comment by tbaddade** [comment]
Ich kann es mir erst einmal nur so erklären, dass das Developer Addon eher dabei war und YDeploy später nachgezogen wurde. Sind denn die Module tatsächlich identisch oder sind das unterschiedliche Versionen?

**Comment by gharlan** [comment]
Also YDeploy macht nichts bzgl der Developer-Pfade, sondern es ist nur in unserer Yak-Struktur enthalten, dass wir in der boot.php des project-Addons den Developer-Pfad auf unseren src-Ordner legen.

Die boot.php des project-Addons wird als letztes geladen (`load: late`).
Wenn vorher ein Fehler auftritt, wäre der Pfad also noch nicht gesetzt. 
Gleichzeitig wundert mich aber, wenn in dem Fall das Developer-Addon trotzdem synchronisiert. Denn das Developer-Addon startet eigentlich frühstens in `PACKAGES_INCLUDED`, und da wurde dann ja auch das `project`-Addon bereits geladen.

War vielleicht das project-Addon kurz mal deaktiviert oder so?

**Comment by alxndr-w** [comment]
Das Project-Addon könnte kurz deaktiviert gewesen sein, ja. Ich melde mich wieder, wenn ich genaueres habe zum Reproduzieren. Im Moment habe ich wenig mit YDeploy-Projekten zu tun.
