### ISSUE TITLE
Umlautproblem: doppelte Dateien

### ISSUE THREAD

**Issue by gharlan** [FriendsOfREDAXO/developer#11]
@tbaddade

> mein vorgehen war. modul mit umlaut angelegt
> input file bearbeitet, war via browser bereits im artikel und klickte auf einen anderen ctype. danach modul hinzufügen

![bildschirmfoto 2013-09-02 um 15 46 03](https://f.cloud.github.com/assets/330436/1095006/4e01b7c8-16da-11e3-8125-a71595395f86.png)

Wahrscheinlich wieder ein Problem mit den UTF-8 NFD Umlauten auf Macs

**Comment by alexplusde** [comment]
Wurde nicht am Redaxo-Tag diskutiert, dass dieses Problem immer noch existiert?

**Comment by gharlan** [comment]
Hier hatte ich es ja auch nur so gelöst, dass man optional die Umlaute ersetzen lassen kann, falls man Probleme damit hat (siehe commit).
Da das scheinbar doch häufiger auftritt, ist es wohl besser den Default-Wert der Option umzukehren. Oder sogar die Option ganz entfernen, also Umlaute immer ersetzen lassen.

**Comment by alexplusde** [comment]
Danke :)

**Comment by gharlan** [comment]
Hoffe, du hast auch in den PR geschaut?
Also habe die Probleme jedenfalls nicht gelöst, sondern die Option wird langfristig abgeschafft, und ist nun default inaktiv.

**Comment by alexplusde** [comment]
Hauptsache ist mir, dass man durch eine Fehlkonfiguration nicht dieses Verhalten provoziert. Im Prinzip könnte man den Dateinamen ja generell durch rex_string::normalize() laufen lassen, oder nicht? Sind ja dieselben Anforderungen wie beim media-Verzeichnis.

**Comment by gharlan** [comment]
Siehe dazu auch #50
