### ISSUE TITLE
Module und Templates werden von Intelephense nicht erkannt

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/developer#110]
**Description / Beschreibung**
Beim Überarbeiten von Modulen und Templates passend zu Änderungen am Namespace mehrerer Addons und Projektcode ist mir aufgefallen, dass IDE-Features wie "Symbol umbenennen" nicht die Module und Templates berücksichtigen.

Mutmaßlich werden sie nicht berücksichtigt, da sie ja normalerweise erst zur Laufzeit und im Kontext geändert werden.

![image](https://github.com/FriendsOfREDAXO/developer/assets/3855487/366c4a25-266f-42f0-86dc-45fe1195a2ed)

Mit dieser Funktion kann ich alle (bekannten) Vorkommen und Verweise von Klassen, Funktionen und Methoden in meinem Projekt umbenennen.

Gibt es eine Möglichkeit, der IDE die Template- und Moduleingabe-/Modulausgabe-Codes bekannt zu machen?

**Comment by gharlan** [comment]
Ich denke, dass das Developer-Addon hier nichts tun kann.
