### ISSUE TITLE
CS-Auto-Fixer

### ISSUE THREAD

**Issue by Hirbod** [FriendsOfREDAXO/developer#35]
Könnte man nicht ggf. den CS Auto-fixer includen und eine Settings-Box "Codestyle beim synchronisieren fixen" einbauen? Das würde einiges erleichtern.

Ich mach das aktuell immer mit dem ATOM Editor, dort ist der CS-Fixer eingebaut, den auch Redaxo verwendet. Ich würde das schön finden. Man könnte auch gleich rumspinnen und auch das selbe für Templates einbauen, und nen HTML Beautify machen.

Nur ein nice-to-have, aber es würde auch das arbeiten mit unterschiedlichen Entwicklern verbessern, da wir dann alle gleichen Code hätten, ohne viel dafür machen zu müssen.

@gharlan

**Comment by gharlan** [comment]
> Nur ein nice-to-have, aber es würde auch das arbeiten mit unterschiedlichen Entwicklern verbessern, da wir dann alle gleichen Code hätten, ohne viel dafür machen zu müssen.

Allerdings auch nur bei den Modulen/Templates. Will man wenn nicht auch eher den anderen Kram im Projekt einheitlich haben? Projektspezifische Dateien etc.?

Ich packe normalerweise in meine Projekte immer eine `.php_cs`-Config, so haben dann alle Entwickler bei dem Projekt die gleiche CS-Config.

Ich glaube auch, das würde sich als Zwischenebene hier im Developer-Addon nicht so gut machen. Hieße ja, wenn du eine Datei änderst, dass dann beim nächsten Sync die Datei wieder neu beschrieben wird.
Würde also #38 noch verstärken.
Klar, es müsste wenn sowieso optional sein. Und nicht alle Editoren meckern so, wie Rudis Editor. (Meiner tut es zum Beispiel nicht.) Aber trotzdem bin ich mir nicht sicher, ob sich das an der Stelle so gut machen würde.

**Comment by Hirbod** [comment]
Ich hab gar keine Reloads. Vllt als Setting? (Default deaktiviert?)

**Comment by gharlan** [comment]
Also ich sehe das nicht im developer-Addon, da ich wie ausgeführt, der Meinung bin, dass man wenn einheitliches CS fürs ganze Projekt haben möchte, und daher das developer-Addon der falsche Ansatz ist.
Daher schließe ich hier.
