### ISSUE TITLE
Session nicht unnötig starten, eventuell plus Option zum Komplett-Deaktivieren

### ISSUE THREAD

**Issue by gharlan** [FriendsOfREDAXO/developer#36]
Schauen, ob man die Requests des MediaManagers (bzw. allgemein Asset-Requests) komplett ignorieren kann.

Außerdem könnte man überlegen, eine Option einzubauen, um Session-Starts durch developer im Frontend gänzlich zu unterbinden.

**Comment by staabm** [comment]
Relates to https://github.com/redaxo/redaxo/issues/1026#issuecomment-279167225

**Comment by gharlan** [comment]
> Außerdem könnte man überlegen, eine Option einzubauen, um Session-Starts durch developer im Frontend gänzlich zu unterbinden.

Oh man, gerade gesehen, dass ich das schon in die letzte Version eingebaut habe. Völlig vergessen. :)
