### ISSUE TITLE
Ständige Editor reloads

### ISSUE THREAD

**Issue by RexDude** [FriendsOfREDAXO/developer#38]
In der Version 3 werde ich quasi ständig von meinem Editor aufgefordert die Dateien die der Developer auspuckt neu zu laden da sie sich geändert haben. Ich habe diese aber nicht geändert sonder ei Modul gespeichert (als Beispiel). Durch den Reload verlieren ich auch jedesmal meine Hstory (Strg+Z).

In Developer 2 war dass nicht so oder nicht so häufig. Evtl. hats ja was mit dem neuen 2 Wege Sync zu tun den du eingebaut hast. Wenns das ist wäre eine Option zum abschalten toll da ich meine Modulnamen sowieso immer übers Backend ändere.

**Comment by gharlan** [comment]
> Evtl. hats ja was mit dem neuen 2 Wege Sync zu tun den du eingebaut hast.

Gerade nochmal in Developer 2 geschaut. Wenn ich das richtig sehe, gab es das da auch schon, falls wir denn das gleiche meinen.
Also auch da wurde schon von den Dateien in die DB, und aber auch umgekehrt synchronisiert. Je nachdem welche Version neuer ist.
Eventuell liegt es aber an dem [Content-Vergleich](https://github.com/FriendsOfREDAXO/developer/blob/2.2.2/classes/class.rex_developer_synchronizer.inc.php#L187) in V2. Scheinbar wurde dort zusätzlich noch gecheckt, ob sich der Content überhaupt unterscheidet, und nur dann die Datei neu geschrieben.

Wobei ich noch nicht verstehe, warum bei dir die Dateien dauernd neu beschrieben werden.
Denn eigentlich wird beim Sync von Datei in DB das `updatedate` auf `filemtime($file)` gesetzt, somit sollte eigentlich dann nicht anschließend die Datei neu geschrieben werden, da dann ja eigentlich die beiden Zeitstempel gleich sein sollten.

**Comment by gharlan** [comment]
Ist es die selbe Datei, die du gerade bearbeitet hast, die dann "geändert" wird?
Oder ist es vielleicht eher so, dass wenn du zum Beispiel die Moduleingabe bearbeitest, anschließend die Datei für die Modulausgabe sich "ändert" und in deinem Editor somit neu eingelesen wird?

**Comment by RexDude** [comment]
Hey danke dass du dich des Problem annimmst. Ob du es glaubst oder nicht: ich versuch grade eben developer2 für R5 zu portieren :D

Ja genau das letztere was du erwähnt hast!

**Comment by gharlan** [comment]
Ok, weil das mit der Modulein- und -ausgabe kann ich mir anhand des Codes erklären.
Muss ich mal schauen, ob sich das leicht fixen lässt.

**Comment by RexDude** [comment]
Das wäre toll :)

**Comment by VIEWSION** [comment]
Ich habe das gleiche Problem seit Mac OS High Sierra und APFS... kann aber Zufall sein. Irgendwas passt mit dem Abgleich der Timestamps nicht mehr. Wenn ich eine Datei extern im Editor ändere und speichere, wird das in die DB mit aktuellem TS übernommen. Die Datei selbst bekommt aber auch einen neuen Modification-TS mit touch()... und da ist das Problem.

Ich konnte das für mich kurzfristig beheben indem ich in der synchronizer.php vorübergehend die Zeile 162 auskommentiert habe:

> if ($dbUpdated != $updated) {
>    foreach ($files as $file) {
>       //touch($file, $updated);
>     }
>    $this->editItem(new rex_developer_synchronizer_item($id, $name, $updated, $updateFiles));
>  }

aber bisher hat es auch problemlos funktioniert. Irgendwo ist da der Wurm drin... bin aber bisher noch nicht drauf gekommen. Vielleicht wird auch irgendwo ein TS gecached oder die Zeit bei MAMP/Systemzeit und MAMP/MySql tickt unterschiedlich....

**Comment by RexDude** [comment]
cool probier ich gleich mal aus...

**Comment by RexDude** [comment]
bringt bei mir nix :(
