### ISSUE TITLE
Modulnamen durch i18n schicken?

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/developer#42]
Ich lege grad einige Module mit `translate:module_1` (1 = id) an. Im Filesystem landen die dann auch mit `translatemodule_1` als Ordnernamen. Könnte das mit dem Übersetzen der ersten Sprache funktionieren?

**Comment by gharlan** [comment]
Ginge schon. Man müsste allerdings drauf achten, ob der Admin denn die Standardsprache als eigene Backendsprache hat, und wenn nicht, müsste man die Sprache kurz wechseln, übersetzen, und dann zurückwechseln..

**Comment by staabm** [comment]
Oder wir fügen eine methode ein, der man die sprache übergeben kann und nutzen diese dann hier fedt mit der sprache1
