### ISSUE TITLE
Styles für die Sliceausgabe im Backend aus kompilierten CSS extrahieren

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/developer#43]
Eventuell wäre das was für das Devleoper-AddOn.

Bsp. damit Teaser (Class `.teaser`) im Backend einigermaßen ordentlich aussehen.

```php
if (rex::isBackend()) {
    $css = \rex_file::get(\rex_path::assets('styles/style.css'));
    preg_match_all('@\.teaser.*?\{.*?\}@s', $css, $matches);
    echo '<style>' . implode(' ', $matches[0]) . '</style>';
}
```

**Comment by gharlan** [comment]
Für mich gehört es hier nicht rein, finde besser, wenn das Addon auf seinen jetzigen Aufgabenbereich beschränkt bleibt.

**Comment by staabm** [comment]
was genau ist das css problem was hier gelöst wird... kann nicht folgen.

**Comment by tbaddade** [comment]
> was genau ist das css problem was hier gelöst wird... kann nicht folgen.

ich hole für das Modul das Frontend-CSS. Damit sieht der Slice im Backend ähnlich dem im Frontend aus.

**Comment by staabm** [comment]
aber sowas kann man ja nicht automatisieren, da es sehr vom css, html und workflow des users abhängt,
