### ISSUE TITLE
Am Ordernamen die Modul Id hängen

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/developer#45]
Ich mache grad ein Upgrade von rex4 auf rex5. Da es am Anfang noch etliche Whoops Fehler regnet, würde es bei diesen Fehlermeldungen `Error rex:///module/23/output:119` helfen, die Modul-Id im Ordnernamen zu sehen.

**Comment by DavidBruchmann** [comment]
ich würde die voranstellen, aber stimme generell zu

**Comment by staabm** [comment]
jepp die url sollte bissl userfreundlicher sein bzw. sollten wir ggf. schauen ob wir sprechendere/userfreundliche texte aus der db selektieren können (modulnamen etc)
