### ISSUE TITLE
Umlautersetzung unvollständig

### ISSUE THREAD

**Issue by DavidBruchmann** [FriendsOfREDAXO/developer#49]
Die Umlautersetzung ist fixiert auf deutsche Umlaute.
Statt dessen sollten eigentlich alle akzentierten Zeichen und Umlaute ersetzt werden.
Dies kann evtl. auf Basis des Zeichen-Bytecodes ohne detailliertes Wissen über einzelne Zeichen stattfinden.

**Comment by staabm** [comment]
Die option ist demnächst deprecated, daher wird da vermutlich nicht mehr viel passieren
https://github.com/FriendsOfREDAXO/developer/pull/46/files

**Comment by DavidBruchmann** [comment]
Mhm, soweit ich das sehe wird mein Issue dann wesentlich wichtiger, da immer Ersetzungen vorgenomen werden müssen.

**Comment by staabm** [comment]
oh du hast recht, genaug das gegenteil von dem was ich gesagt habe ist der Fall ;-).

am besten wäre es wohl mittels iconv und //TRANSLIT o.ä. zu arbeiten

`$name = iconv('UTF-8', 'ASCII//TRANSLIT', $name);`

damit sollte - wenn die aktuelle locale richtig eingestellt ist - ein passendes ASCII zeichen verwendet werden.

**Comment by staabm** [comment]
siehe https://github.com/FriendsOfREDAXO/developer/pull/50 bitte gegentesten
