### ISSUE TITLE
yForm Email Templates

### ISSUE THREAD

**Issue by polarpixel** [FriendsOfREDAXO/developer#52]
Es wäre eine feine Sache, wenn man auch die Mail Templates von yForm dateibasiert mit dem Developer-AddOn bearbeiten könnte.

Lg, Peter.

**Comment by Hirbod** [comment]
Sehr gute Idee

**Comment by alexplusde** [comment]
So exzellent - ich weiß gar nicht, warum ich erst jetzt ein +1 dafür geben würde!

**Comment by jelleschutter** [comment]
Habe einen PR erstellt. Bin mir jedoch nicht sicher bei folgenden Punkten:
1. Sollte dies überhaupt in diesem AddOn gelöst werden oder im yForm?
2. Habe ich die Ergänzugen für yForm an allen nötigen Stellen hinzugefügt?

**Comment by alexplusde** [comment]
ich tendiere bei 1. dazu, das hier zu lösen. Wenn @gharlan wieder zurück ist, wird er sicher dazu was sagen können.

Danke schon mal @jelleschutter

**Comment by gharlan** [comment]
So wie es ausschaut, benötigen wir erst ein updatedate-Feld für die E-Mail-Templates in YForm: https://github.com/FriendsOfREDAXO/developer/pull/82#pullrequestreview-337863809

**Comment by alexplusde** [comment]
@dergel können wir hier mergen? Muss die Mindesanforderung für REDAXO in developer dann hochgesetzt werden?
