### ISSUE TITLE
Pfade in whoops in die tatsächlichen Pfade umbiegen

### ISSUE THREAD

**Issue by gharlan** [FriendsOfREDAXO/developer#53]
In Whoops werden bei Fehlern in Modulen/Templates nicht der Code-Ausschnitt angezeigt, und die Datei ist mit diesem `rex://`-Pfad verlinkt (zum Öffnen im Editor).
Daher sollte das Developer-Addon die Pfade auf die tatsächlichen Pfade umbiegen, bevor whoops diese verarbeitet.

![screenshot 2017-10-13 11 45 41](https://user-images.githubusercontent.com/330436/31540509-2958f25e-b00c-11e7-835a-fd12cb3f1fc0.png)

**Comment by staabm** [comment]
ich denke dass sollten wir zum teil auch im core machen
(d.h. die exception / die message anreichern um "fehler in template 4" o.ä.)

**Comment by tbaddade** [comment]
> ich denke dass sollten wir zum teil auch im core machen

Dann lasst uns das Issue zum Core schieben.

**Comment by gharlan** [comment]
Developer muss hier auf jeden Fall was machen. Der Core kennt die Developer-Pfade nicht, die werden aber insbesondere für die Verlinkung benötigt. Und darum geht es mir in diesem Issue in erste Linie!

Des Weiteren geht es mir um den fehlenden Code-Ausschnitt, der mir eben erst aufgefallen ist. Da ist für mich vor allem die Frage, was dort angezeigt werden sollte. Der Original-Code mit Rex-Vars, oder der tatsächlich ausgeführte PHP-Code?
So oder so könnte dies aber in der Tat der Core eventuell bereits übernehmen.

> die message anreichern um "fehler in template 4"

Das ist mir weniger wichtig, habe ich aber natürlich nichts gegen, wenn das jemand baut!
Mir persönlich reicht diesbezüglich eigentlich schon der aktuelle Pfad (`rex:///templates/4`), oder auch dann der Developer-Pfad (`redaxo/data/addons/developer/templates/00 . Header/template.php`

**Comment by staabm** [comment]
uns core entwicklern reicht der pfad, normale redaxo programmierer können den vermutlich nicht deuten... ich mach mal nen separates issue auf

**Comment by gharlan** [comment]
Hat sich erledigt mit der Editor-Integration in 5.7 und #72
