### ISSUE TITLE
Template Duplikate

### ISSUE THREAD

**Issue by eaCe** [FriendsOfREDAXO/developer#58]
Hi,

ich bin sicher das folgendes Problem **kein** Addon Bug ist, aber mich würde interessieren, ob schon ein mal jemand etwas ähnliches erlebt hat und wenn ja, gibt es hierzu irgendwelche Tipps?

Ich habe eben eine neue Redaxo Instanz lokal installiert. So wie schon etliche male zuvor. 
Redaxo 5.4.0 und Developer 3.6.1. 
Diese Konstellation habe ich auch schon bei 2 anderen Projekten, auch lokal, bei denen alles prima läuft.

Nun passiert folgendes:
Pro reload der Seite oder pro Seitenwechsel wird im Template Ordner munter das Default Template dupliziert. Nach 5 Minuten habe ich nun 316 default Templates im Ordner liegen.

![template-duplicates](https://user-images.githubusercontent.com/2708231/32688241-8e3f5758-c6cd-11e7-82de-90976a491413.PNG)

**Comment by fezoeller** [comment]
Genau das gleiche Problem wollte ich gerade auch schildern.
Ich habe mal rumprobiert und bin zu einem workarround gekommen, wie man es umgehen kann.
1. Das Addon löschen
1a. angelegte Templates gelöscht und AutoincrementWert berichtigt (nicht nötig, aber habe trotzdem gemacht)
2. Version  3.4.1 heruntergeladen/installiert
3. Danach das update auf 3.6. gemacht.
Im developerAddon gibt es ja einige Einstellungen, die habe ich dann nicht mehr angefasst. Meine Vermutung ist das die Funktion "Ordnernamen mit ID als Suffix" das Problem verursacht (aber nur ne Vermutung)

**Comment by schuer** [comment]
@eaCe Schön, dich mal wieder hier zu sehen!
Hast du das Problem auch mit den älteren Versionen von developer, oder nur mit der 3.6? Ich würde sonst empfehlen, @fezoeller s Workaround auszuprobieren oder vorerst bei Version 3.5 zu bleiben.
— Gregor hat gerade einen längeren Urlaub angefangen, ein Bugfix könnte also ein Weilchen brauchen.

**Comment by schuer** [comment]
Siehe auch redaxo/redaxo#1469

**Comment by eaCe** [comment]
Danke gleichfalls @schuer ;) Schön wieder mit Redaxo statt Wordpress zu arbeiten :)
Werde mich im kommenden Jahr auch wieder in die Community integrieren, war etwas chaotisch…

Die Lösung die in redaxo/redaxo#1469 funktioniert prima!

**Comment by gharlan** [comment]
@eaCe @fezoeller @frood @martinm79 @tyrant88 
Sehe ich das richtig, dass euch alle das in einer lokalen Installation auf Windows betraf?
Oder war es bei irgendjemand auch Linux oder Mac?

**Comment by martinm79** [comment]
Richtig. Bei mir war es auf Windows lokalhost.

**Comment by tyrant88** [comment]
Windows, lokal.

**Comment by eaCe** [comment]
Dito! Win lokal...

**Comment by frood** [comment]
Jupp, local auf Win7 und xampp

**Comment by darwin26** [comment]
HI... bei unseren win jungs, trott das problem auch auf.
Mac jedoch nicht...

der workaround von @frood hilft (vorerst)

> Vor dem Installieren des Developer-Addons in der Datei:
> 
> \redaxo\src\addons\developer\install.php
> 'dir_suffix' => false,
> setzen

**Comment by xong** [comment]
Lösung ist comitted: https://github.com/FriendsOfREDAXO/developer/commit/15da9ac1fbeb273aaa6e7bcbd90da319cd7ca7da#diff-5257486c229f734803f7dbf2bcbac5c8

**Comment by gharlan** [comment]
@xong Sehr cool, danke! Habs noch nicht ganz kapiert, schaue ich mir aber auch nochmal genauer an.

Allgemein wäre mir aber lieber, wenn wir zukünftig hier im Repo den Weg über PRs gingen.

**Comment by schuer** [comment]
Bei FOR generell gerne mittels PRs. Einfach deshalb, weil es dann sichtbarer wird und das 4-Augen-Prinzip fördert.

**Comment by staabm** [comment]
Da das ein generelles problem ist und öfter auftaucht... können wir ein release machen @gharlan ?
