### ISSUE TITLE
Module/Templates aus Tabelle werden nicht in files gesynced bei Installation in eine bestehende Seite

### ISSUE THREAD

**Issue by aeberhard** [FriendsOfREDAXO/developer#60]
Bei Installation in eine bereits bestehende REDAXO-Installation mit vorhandenen Templates und Modulen
werden die PHP-Codes nicht ins File-System geschrieben.

Es werden nur die Ordner erstellt mit Inhalt z.b. 1.rex_id aber die Input/Output bei Modulen und die yml fehlen. Ebenso bei den Templates. 

Es müssten alle Module und Templates manuell editiert und gespeichert werden um alles in die Files zu 
synchronisieren. 

Siehe auch https://github.com/FriendsOfREDAXO/demo_fullpage/issues/8

**Comment by tbaddade** [comment]
Nimm mal unter den Einstellungen  die Suffixe Optionen raus. Bisher hat Developer eigentlich sehr gut funktioniert, egal wann es ins Projekt gelegt wurde.

**Comment by aeberhard** [comment]
Hallo Thomas, das Addon tut ja sonst auch das was es soll.
Hätte nur erwartet alle Templates und Module sofort im File-System zu finden.
Eine Code-Zeile würde den "Fehler" beheben :)

**Comment by tbaddade** [comment]
> Hätte nur erwartet alle Templates und Module sofort im File-System zu finden.

Das sollte eigentlich so sein. Nach der Installation sollten die Module und Templates bereits im Filesystem liegen. Die Module und Templates brauchst du nicht nochmals editieren und speichern.

**Comment by aeberhard** [comment]
Das ganze ist sehr misteriös. Hatte noch ein paar mal diesen Fehler also keine Module und Templates, aber jetzt neu installiert und den Fehler mit den Duplikaten.
Ich mache hier mal zu!
