### ISSUE TITLE
Dokumentation auch via REX erreichbar machen

### ISSUE THREAD

**Issue by madiko** [FriendsOfREDAXO/developer#61]
Hallo,

ich fände super, wenn aus der readme.md der Part ab "Benutzung" als "Dokumentation" auch via REX erreichbar wäre. Mein Vorschlag: Ähnlich zum MForm-AddOn als eigenen "Dokumentation"-Tab im Backend. Zudem noch ein Link hier zu git. Perfekt!

https://github.com/FriendsOfREDAXO/developer#benutzung

Viele Grüße und bitte weiter so!
Franziska :-)

**Comment by staabm** [comment]
soweit ich mich erinnere sollte alles was du hier unter README findest automatisch im redaxo angezeigt werden wenn du von der Addon page über das "?" zur hilfe des addons springst

**Comment by madiko** [comment]
Das schon. Doch da erwarte ich nur die Doku zur Installation und das Change-Log zu den einzelnen Releases (was sehr sinnvoll dort ist und von den meisten Entwicklern auch so gehandhabt wird).

Die Doku zur Anwendung im Alltag / laufenden Betrieb ist bei den meisten guten AddOns - sinnvollerweise - beim AddOn selbst hinterlegt. 

Diese Logik finde ich ausgezeichnet und schlug es daher auch für dieses AddOn vor.

**Comment by aeberhard** [comment]
Im Demo-Addon gibt es ein plugin documentation
https://github.com/FriendsOfREDAXO/demo_addon

Damit kann man einem Addon im Style von yform eine Dokumentation
mit lokalen md-Dateien (im Addon-Verzeichnis) verpassen.

Wird auch hier verwendet https://github.com/FriendsOfREDAXO/xoutputfilter

Sehe gerade das demo_addon ist gar nicht im Installer drin ...

**Comment by madiko** [comment]
Demo-AddOn wäre super! Danke @aeberhard.

**Comment by aeberhard** [comment]
@madiko das demo_addon ist jetzt auch im Installer verfügbar.
Einfach mal installieren und dann noch das plugin documentation installieren.
Die Dokumentation kann beschreibt wie das plugin für eigene Addons angepasst
werden kann.

**Comment by madiko** [comment]
Perfekt!

Doch zurück zu diesem AddOn: Was meint Ihr? Ich fände die Doku wirklich sehr hilfreich. Danke.

**Comment by tbaddade** [comment]
> Das schon. Doch da erwarte ich nur die Doku zur Installation und das Change-Log zu den einzelnen Releases (was sehr sinnvoll dort ist und von den meisten Entwicklern auch so gehandhabt wird).

@madiko 
Das kann man auch anders sehen. Auf Github werden viele Docus direkt in der Readme notiert.
