### ISSUE TITLE
theme und developer Addons zusammenführen

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/developer#63]
Scheinbar überschneiden sich ja die Anwendungsfälle - mir ist nicht klar, warum ich einmal im Theme-Addon-Pfad und einmal im Data-Pfad die Templates und Module bereithalte. Auch die Konfigurationsmöglichkeiten sind dieselben.

**Comment by IngoWinter** [comment]
Developer Addon: ermöglicht editieren von Templates, Modulen etc im Dateisystem
Theme Addon: stellt eine sinnvolle Ordnerstruktur für projektbezogene Assets zur Verfügung

Du kannst beide Addons einzeln verwenden, sie haben nichts miteinander zu tun. Das theme Addon ändert nur den Pfad, in dem das Developer Addon seine Dateien ablegt.

**Comment by skerbis** [comment]
Das doppelte Syncen ist dennoch mehr als fragwürdig.

**Comment by gharlan** [comment]
Ich sehe da auch keine Überschneidung. Theme-Addons ist ja eher eine Alternative zum project-Addon. Aber das developer-Addon braucht man so oder so.
