### ISSUE TITLE
codeeditor via whoops unterstützen

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/developer#68]
wäre super wenn das addon eine konfig anbieten würde, wo man seinen editor einstellen kann, sodass dann in whoops fehlerseiten, die Dateien verlinkt werden, damit sie direkt im editor/IDE geöffnet werden können.

https://github.com/filp/whoops/blob/master/docs/Open%20Files%20In%20An%20Editor.md

**Comment by staabm** [comment]
ich denke für den rex core selbst wäre das ein zu spezielles feature, aber im context des developer addons macht es durchaus sinn.

**Comment by staabm** [comment]
Ich denke, eine UI für dieses setting zu haben wäre wichtig, da es die produktivität deutlich verbessert. wenn es nur im core in der config.yml bleibt würden viele es nicht sehen, denke ich.

wie wäre es das setting im core via config.yml zu ermöglichen und im developer addon ein Eingabefeld dafür bereitzustellen?

**Comment by gharlan** [comment]
Das Ding ist: Wenn ich heute das developer-Addon frisch erstellen würde, würde ich einen anderen Namen wählen. "developer" ist mir da viel zu allgemein. Ich hatte das Addon aber damals von Wolfgang "übernommen", und es hieß schon so.
Trotzdem versuche ich im Addon den Fokus zu behalten, wofür es zuständig ist: Die Synchronisation zwischen DB und Dateiebene.
Möchte es nicht aufblasen zu einem allgemeinen Addon, mit allerlei nützlichen Dingen für die Developer.

Deswegen sehe ich diese Einstellung nicht hier im Addon.

Wenn es mit UI sein soll (ich finde das nicht notwendig, würde mich aber auch nicht gegen sperren), dann würde ich es einfach im Setup und/oder unter System aufnehmen, aber direkt im Core.

**Comment by schuer** [comment]
Lass uns doch das AddOn umbenennen? Ist ja keine allzu große Sache.

**Comment by gharlan** [comment]
Habe ich auch schon überlegt, aber irgendwie hat man sich an den Namen auch sehr gewöhnt. ;)
Bin mir unsicher.

**Comment by staabm** [comment]
ok, ich werds direkt im core versuchen... vllt macht es ja sinn die einstell-möglichkeit des editors direkt in der whoops fehlerseite zu machen, mit nem settings-symbol oder so... 

dann wäre das setting zumindest an einer stelle wo es in kombination mit den errors zusammen in verbindung gebracht werden kann (und auch auffällt)

**Comment by staabm** [comment]
@gharlan was man im speziellen für die developer philosopie machen könnte: wenn ein fehler aus einem php source kommt, den man via developer addon auch als datei verfügbar hat (module, templates etc), dann könnte das developer addon die entsprechenden pfade für whoops liefern, sodass man den modul/template/... code direkt im editor öffnet...

**Comment by bloep** [comment]
@staabm #53
