### ISSUE TITLE
Module/Templates via file includen statt streamwrapper

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/developer#70]
Wäre es möglich, dass redaxo bei installiertem developer die module und templates aus dem filesystem included?

Solange php bei stream wrappeen noch keinen opcache verwendet könnte dies einen performance vorteil darstellen (these die noch zu validieren ist)

**Comment by staabm** [comment]
ok, da muss man mal blackfire messen mit. danke für den input.

**Comment by gharlan** [comment]
Das Developer-Addon kann hier aus meiner Sicht nichts tun. So oder so müssen die Dateien erst geparst werden (REX_VARs), und das ist bereits nicht mehr Part vom Developer-Addon. Ob somit anschließend mit einem Stream oder mit echten Dateien gearbeitet wird, müsste im Core oder im structure-Addon entschieden werden.
