### ISSUE TITLE
Viele file_exists calls

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/developer#76]
Bei aktiviertem developer addon, dominiert der synchronizer mit file_exists calls.

![b0d19cf8-d094-4256-b1c1-6d22970a7a15](https://user-images.githubusercontent.com/120441/50528067-713ea000-0aec-11e9-9113-db1bae9df103.jpeg)

Alle top3 plätze sind vom default synchronizer

**Comment by Hirbod** [comment]
wurde mit #77 gefixed

**Comment by staabm** [comment]
Ich hatte das issue noch offen gelassen, da nichg alle weg sind bzw. Nur ein teil davon.

Aber wegen mir können wir es geschlossen lassen... ist aktuell „schnell genug“

**Comment by Hirbod** [comment]
Oh sorry! Aber ja, deine Optimierungen sind überall deutlich zu spüren :)
