### ISSUE TITLE
update auf R5.7 - kein syncen der Daten mehr

### ISSUE THREAD

**Issue by darwin26** [FriendsOfREDAXO/developer#80]
Hi,
habe gestern auf R5..7 upgedatet. Seitdem geht kein syncen mehr mit dem Developer AddOn.
DeInstall + löschen der /data/addons/developer Verzeichnis
Danach neu heruntergeladen und installiert.
- /data/addons/developer --> Verzeichnis wird gar nicht erst wieder angelegt!

kannst Du das nachvollziehen...

PHP 7.2.10
ist ein bestehendes System - werde es auch blank mal testen

**Comment by darwin26** [comment]
bin wieder rückwärts auf R56 - hier funktioniert alles mit dem developer Addon ...

**Comment by gharlan** [comment]
Bei mir funktioniert das Developer-Addon.

**Comment by darwin26** [comment]
*grmpf* - sry - lokal funktionierts einwandfrei.
Somit liegts mal wieder am Hoster ...

close. Danke @gregor

**Comment by staabm** [comment]
@darwin26 wenn die fehlerursache "beim hoster" bekannt ist, bitte hier zurückmelden.. ggf. kann man ja da was machen

**Comment by darwin26** [comment]
erste meldung - allerdinsg vom URL AddOn:
AddOn "url" konnte aus folgendem Grund nicht aktualisiert werden:
Es wird die PHP-Extension intl benötigt!

kann aber nicht mit dem deeveloper AddOn zusammenhängen? ...
(bin grad noch am testen) ...

**Comment by darwin26** [comment]
blank redaxo cms 57 nur mit developer + theme addon - funktioniert.
Liegt an was anderem. Danke und sry... (definitv close) ;) ...

**Comment by darwin26** [comment]
*strange* ...
- Lokal / nochmal getestet - das syncen der Daten (modul Input/ouput) funktioniert
d.h. Wenn ich die Datei /theme/private/redaxo/modules/01 - testmodul/ output.php
editieren und speichere - ists auch in der DB und im Redaxo CMS

- HOST / nochmal getestet - das syncen der Daten (modul Input/ouput) funktioniert **hier nicht**
d.h. Wenn ich die Datei /theme/private/redaxo/modules/01 - testmodul/ output.php
editieren und speichere - ists weder in der DB noch im Redaxo CMS.

**Comment by darwin26** [comment]
trotz deinstallieren und per Hand aufräumen (/data/addons/developer/)
und neu installieren des developers - stehen im /data/addons/developer/
wird das Dir Modules gar nicht angelegt...

und es sind plötzlich "alte" Templates Daten im /data/addons/developer/templates/ ....

schreibt das developer noch iwo was hin /cache/? config? ... oder ähnl.
mich wundert es gerade, woher die alten Daten kommen ....

*heute nicht mein tag*  - *strange*

**Comment by darwin26** [comment]
definitiv nun close...

Kollege hat die login.php bearbeitet - das in R56 noch funktionierte.
in R57 leider nicht mehr - da scheinbar hier sich etwas geändert hat ...

sry - unser Fehler.

Danke
