### ISSUE TITLE
E-Mail-Templates Zeilenumbrüche

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/developer#93]
Ich habe die developer-Synchronisierung in Verdacht, dass diese versehentlich newline-Steuerzeichen eingefügt hat in Kombination mit meinem Editor, die vorher nicht drin waren.

![image](https://user-images.githubusercontent.com/3855487/102473365-a933aa80-4057-11eb-8527-fd841928dfa5.png)

Ich behalte das mal im Auge.

**Comment by gharlan** [comment]
Hast du hier noch irgendwas rausgefunden?

**Comment by alxndr-w** [comment]
Leider nein.
