### ISSUE TITLE
assets synchronisieren

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/developer#94]
Es wäre super, wenn man beim Entwickeln nicht ständig Acht geben müsste, die Änderungen im addon/assets/-Ordner mit denen aus dem Frontend zu synchronisieren.

Weil der assets-Ordner im addon-Ordner "näher" in der Editoroberfläche ist und auch hochgeladen wird, wäre mir diese Richtung besonder wichtig - vielleicht könnte man aber auch die Richtung "tauschen". 

Ich weiß nicht, wie's mit der Performance ist bei vielen assets - vermutlich sollte man erstmal vergleichen, welche Dateien neuer sind / sich geändert haben und ggf. gelöscht wurden.

**Comment by gharlan** [comment]
Das sehe ich eher im Core.
- einerseits da die assets-Dateien bereits ein Core-Feature sind, und daher aus meiner Sicht auch der Core angenehmes Entwickeln daran unterstützen sollte
- andererseits weil ich den Aufgabenbereich dieses Addons relativ eng setzen/lassen möchte. Den Namen "developer" finde ich nicht gut gewählt (da zu allgemein), hatte den damals aber so übernommen und würde ihn jetzt auch nicht ändern. Und ich gebe zu, dass du hier mit dem Asset-Syncing schon relativ nah am Thema bist, aber ich würde es hier gerne trotzdem bei dem Syncing von Datenbankinhalten ins Dateisystem (mit eigenen Dateien des developer-Addons) belassen.

**Comment by alxndr-w** [comment]
Mir egal, wo es umgesetzt wird. Man könnte ja auch einen Schalter in der package.yml setzen, sodass es nicht bei jedem Aufruf alle Assets betrifft, sondern nur die nötigen.

Eben ein Verhalten, das ich hier am ehesten vermutet hätte.

**Comment by gharlan** [comment]
Wie oben geschrieben, möchte ich den Aufgabenbereich dieses Addons eng halten.
